version: '3.8'

services:

  # Use postgres/example user/password credentials
  db:
    image: postgres:13.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      # localeを設定したい理由がないので、localeを設定しない (localeをCに設定する)
      # postgresql.org/docs/13/locale.html 23.1.2. Behavior
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    networks:
      - development_network
  
  cache:
    image: redis:6.2.1
    restart: always
    ports:
      - "6379:6379"
    networks:
      - development_network

  db-management-client:
    # データベース操作が可能なWeb UIを提供するimage
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
    networks:
      - development_network

  smtp:
    # SMTPサーバとしての機能と受け取ったメールを確認するWeb UIを提供するimage
    image: schickling/mailcatcher:latest
    restart: always
    ports:
      - "1080:1080" # Web UIのポート
      - "1025:1025" # APIのポート
    networks:
      - development_network

  storage:
    # AWS s3互換のモックサーバとしての機能と管理用のWeb UIを提供するimage
    image: minio/minio:RELEASE.2022-02-01T18-00-14Z
    container_name: "storage"
    entrypoint: sh -c "
        mkdir -p /data/identity-images;
        mkdir -p /data/.minio.sys/buckets/identity-images;
        mkdir -p /data/career-images;
        mkdir -p /data/.minio.sys/buckets/career-images;
        minio server /data --console-address ':37135'"
    ports:
      - 37135:37135 # 管理画面のポート
      - 9000:9000 # APIのポート
    environment:
      - MINIO_ROOT_USER=minio # 管理画面のユーザ、APIのアクセスキー
      - MINIO_ROOT_PASSWORD=password # 管理画面のパスワード、APIのシークレット
      - MINIO_DOMAIN=storage
    volumes:
      - minio:/data
    networks:
      development_network:
        aliases:
          - identity-images.storage
          - career-images.storage

  elasticsearch:
    build:
      context: ./elastic_search_with_plugins
      dockerfile: Dockerfile
    restart: always
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - development_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    restart: always
    ports:
      - 5601:5601
    networks:
      - development_network

volumes:
  minio:
  es-data:
    driver: local

networks:
  development_network: