# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "8081:8080"

