[package]
name = "admin_service"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-redis-session = "0.2.2"
async-session = "3.0.0"
axum = { version = "0.5.3", features = ["headers", "json", "multipart"] }
chrono = "0.4.19"
common = { path = "../common" }
dotenv = "0.15.0"
entity = { path = "../entity" }
headers = "0.3.4"
image = "0.24.0"
num_cpus = "1.13.0"
once_cell = "1.8.0"
serde = { version = "1.0.127", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.8"
tower-cookies = { version = "0.6.0", features = ["axum-core", "signed"] }
tower-http = { version = "0.2.2", features = ["trace"] }
tracing = "0.1.26"
tracing-subscriber = "0.3.1"
