[package]
name = "admin_service"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
entity = { path = "../entity" }
axum = { version = "0.5.0", features = ["headers", "json", "multipart"] }
headers = "0.3.4"
hyper = { version = "0.14.11", features = ["full"] }
tokio = { version = "1.10.0", features = ["full"] }
tower = "0.4.8"
http-body = "0.4.3"
tracing = "0.1.26"
tracing-subscriber = "0.3.1"
tower-http = { version = "0.2.2", features = ["trace"] }
dotenv = "0.15.0"
num_cpus = "1.13.0"
serde = { version = "1.0.127", features = ["derive"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
chrono = "0.4.19"
once_cell = "1.8.0"
async-session = "3.0.0"
async-redis-session = "0.2.2"
tower-cookies = { version = "0.6.0", features = ["axum-core", "signed"] }
cookie = "0.16.0"
rust_decimal = "1.19.0"
image = "0.24.0"
regex = "1.5.5"
bytes = "1.1.0"