[package]
name = "admin_service"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-redis-session = "0.2.2"
async-session = "3.0.0"
axum = { version = "0.5.6", features = ["headers", "json", "multipart"] }
chrono = "0.4.19"
common = { path = "../common" }
dotenv = "0.15.0"
entity = { path = "../entity" }
headers = "0.3.7"
image = "0.24.1"
num_cpus = "1.13.1"
once_cell = "1.10.0"
opensearch = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tower-cookies = { version = "0.6.0", features = ["axum-core", "signed"] }
tower-http = { version = "0.3.0", features = ["trace"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
uuid = { version = "1.0.0", features = ["serde", "v4"] }
