AWSTemplateFormatVersion: "2010-09-09"
# 本番、開発の両環境で同じ成果物格納場所を参照するので、このテンプレートはProd、Devと分けて作成しない。
# スタック名はArtifactsStoreとする。
Resources:
  # frontendの成果物の格納用S3バケット
  CcsUserAppCiResultStorage:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: "ccs-user-app-ci-result-storage"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CcsAdminAppCiResultStorage:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: "ccs-admin-app-ci-result-storage"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    # backendの成果物の格納用のECR
    CcsAdminServiceRepository:
      Type: "AWS::ECR::Repository"
      Properties:
        RepositoryName: "ccs-admin-service"
        EncryptionConfiguration:
          EncryptionType: "AES256"
        ImageScanningConfiguration:
          ScanOnPush: false
        ImageTagMutability: "IMMUTABLE"
        LifecyclePolicy:
          RegistryId: !Ref AWS::AccountId
Outputs:
  ApplicationClusterArn:
    Value: !GetAtt CcsAdminServiceRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-AdminServiceRepositoryUri"
