AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    ElastiCacheCacheCluster:
        Type: "AWS::ElastiCache::CacheCluster"
        Properties:
            CacheNodeType: "cache.t4g.micro"
            Engine: "redis"
            EngineVersion: "7.0.7"
            NumCacheNodes: 1
            PreferredAvailabilityZone: !Sub "${AWS::Region}a"
            PreferredMaintenanceWindow: "mon:15:30-mon:16:30"
            CacheParameterGroupName: "default.redis7"
            CacheSubnetGroupName: "sg-1691159446460"
            AutoMinorVersionUpgrade: true
            VpcSecurityGroupIds: 
              - "sg-02826e29d4759cd39"
            SnapshotRetentionLimit: 0
            SnapshotWindow: "14:01-15:01"
            ClusterName: "ccs-redis-cluster-001"

    ElastiCacheReplicationGroup:
        Type: "AWS::ElastiCache::ReplicationGroup"
        Properties:
            ReplicationGroupId: "ccs-redis-cluster"
            ReplicationGroupDescription: " "
            NumNodeGroups: 1
            AutomaticFailoverEnabled: false
            SnapshotRetentionLimit: 0
            SnapshotWindow: "14:01-15:01"
            CacheNodeType: "cache.t4g.micro"
            TransitEncryptionEnabled: true
            AtRestEncryptionEnabled: true
            MultiAZEnabled: false

    ElastiCacheSubnetGroup:
        Type: "AWS::ElastiCache::SubnetGroup"
        Properties:
            Description: "Created from RDS create flow"
            CacheSubnetGroupName: "sg-1691159446460"
            SubnetIds: 
              - "subnet-014c176888d2e5d77"

    ElastiCacheUser:
        Type: "AWS::ElastiCache::User"
        Properties:
            UserId: "default"
            UserName: "default"
            Engine: "redis"
            AccessString: "on ~* +@all"
            NoPasswordRequired: true


