AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required parameters
        Parameters:
          - Environment
          - UserServiceAccessRestrictionCustomHeaderValue
          - AdminServiceAccessRestrictionCustomHeaderValue
      - Label:
          default: Optional parameter
        Parameters:
          - ServiceDomainName
Parameters:
  # prodの場合はスタック名に"ProdRequestController"、devの場合はスタック名に"DevRequestController"を指定する
  Environment:
    Type: String
    AllowedValues:
      - prod
      - dev
  ServiceDomainName:
    Type: String
    Default: career-change-supporter.com
    Description: |-
      ${ServiceDomainName} and admin.${ServiceDomainName} are registered for prod.
      dev.${ServiceDomainName} and admin.dev.${ServiceDomainName} are registered for dev.
      api.${ServiceDomainName} for prod or api.dev.${ServiceDomainName} for dev is used for api access
    AllowedPattern: ^([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.)+[a-zA-Z]{2,}$
  UserServiceAccessRestrictionCustomHeaderValue:
    NoEcho: true
    Type: String
    Description: Enter same value as the one you set on ALB for user service
    AllowedPattern: ^[a-zA-Z0-9]{32}$
  AdminServiceAccessRestrictionCustomHeaderValue:
    NoEcho: true
    Type: String
    Description: Enter same value as the one you set on ALB for admin service
    AllowedPattern: ^[a-zA-Z0-9]{32}$
Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]
# CloudFrontで利用するACMとWAFはus-east1でしか作成できないため、us-east1で作成する
Resources:
  CcsUserServiceRequestController:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        PriceClass: "PriceClass_All"
        HttpVersion: "http2"
        WebACLId: !GetAtt CcsUserServiceWaf.Arn
        Aliases:
          - !If [IsProd, !Ref ServiceDomainName, !Sub "dev.${ServiceDomainName}"]
        ViewerCertificate:
          AcmCertificateArn: !Ref CcsUserServiceCertificate
          CloudFrontDefaultCertificate: false
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
        Logging:
          Bucket: !Sub "${CcsUserServiceLogStorage}.s3.amazonaws.com"
          IncludeCookies: false
          Prefix: ""
        DefaultRootObject: "index.html"
        Origins:
          - Id: !Join [".", [!If [IsProd, "api", "api.dev"], !Ref ServiceDomainName]]
            DomainName: !Join [".", [!If [IsProd, "api", "api.dev"], !Ref ServiceDomainName]]
            CustomOriginConfig:
              OriginProtocolPolicy: "https-only"
              HTTPSPort: 443
              OriginSSLProtocols:
                - "TLSv1.2"
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
            OriginPath: ""
            OriginCustomHeaders:
              - HeaderName: "X-Ccs-Alb-Access-Restriction"
                HeaderValue: !Ref UserServiceAccessRestrictionCustomHeaderValue
            OriginShield:
              Enabled: false
            ConnectionAttempts: 3
            ConnectionTimeout: 10
          - Id: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-user-app.s3.ap-northeast-1.amazonaws.com"]]
            DomainName: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-user-app.s3.ap-northeast-1.amazonaws.com"]]
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginShield:
              Enabled: false
            ConnectionAttempts: 3
            ConnectionTimeout: 10
        DefaultCacheBehavior:
          AllowedMethods:
            - "HEAD"
            - "GET"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          SmoothStreaming: false
          TargetOriginId: !Sub "${S3Bucket2}.s3.ap-northeast-1.amazonaws.com"
          ViewerProtocolPolicy: "https-only"
        CacheBehaviors:
          - AllowedMethods:
              - "HEAD"
              - "DELETE"
              - "POST"
              - "GET"
              - "OPTIONS"
              - "PUT"
              - "PATCH"
            Compress: true
            CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
            OriginRequestPolicyId: "216adef6-5c7f-47e4-b989-5492eafa07d3"
            PathPattern: "/api/*"
            SmoothStreaming: false
            TargetOriginId: "api.career-change-supporter.com"
            ViewerProtocolPolicy: "https-only"
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: "/"
            ResponseCode: "200"
            ErrorCachingMinTTL: 10
        Comment: ""
        Enabled: true
        Restrictions:
          GeoRestriction:
            RestrictionType: "none"
        IPV6Enabled: true
  CcsUserServiceWaf:
    Type: "AWS::WAFv2::WebACL"
    Properties:
      Name: "CcsCloudFrontWebAcl"
      Description: ""
      DefaultAction:
        Block: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: "CcsCloudFrontWebAcl"
      Scope: "CLOUDFRONT"
      Rules:
        - Name: "OnlyAllowFromMyIP"
          Priority: 0
          Action:
            Allow: {}
          Statement:
            OrStatement:
              Statements:
                - IPSetReferenceStatement:
                    ARN: !GetAtt WAFv2IPSet.Arn
                - IPSetReferenceStatement:
                    ARN: !GetAtt WAFv2IPSet2.Arn
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "OnlyAllowFromMyIP"
    CcsUserServiceCertificate:
      Type: "AWS::CertificateManager::Certificate"
      Properties:
        DomainName: "career-change-supporter.com"
        SubjectAlternativeNames:
          - "career-change-supporter.com"
        DomainValidationOptions:
          - DomainName: "career-change-supporter.com"
            ValidationDomain: "career-change-supporter.com"
        CertificateTransparencyLoggingPreference: "ENABLED"
  CcsUserServiceLogStorage:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "ccs-cloudfront-logs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerPreferred"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CloudFrontDistribution2:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - "admin.career-change-supporter.com"
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: "https-only"
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - "TLSv1.2"
            DomainName: "api.career-change-supporter.com"
            Id: "api.career-change-supporter.com"
            OriginCustomHeaders:
              - HeaderName: "X-Admin-Ccs-Alb-Access-Restriction"
                HeaderValue: "2233ef9458ba4d7ca88886c794b75c26"
            OriginPath: ""
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            DomainName: !Sub "${S3Bucket}.s3.ap-northeast-1.amazonaws.com"
            Id: !Sub "${S3Bucket}.s3.ap-northeast-1.amazonaws.com"
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          AllowedMethods:
            - "HEAD"
            - "GET"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          SmoothStreaming: false
          TargetOriginId: !Sub "${S3Bucket}.s3.ap-northeast-1.amazonaws.com"
          ViewerProtocolPolicy: "https-only"
        CacheBehaviors:
          - AllowedMethods:
              - "HEAD"
              - "DELETE"
              - "POST"
              - "GET"
              - "OPTIONS"
              - "PUT"
              - "PATCH"
            Compress: true
            CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
            OriginRequestPolicyId: "216adef6-5c7f-47e4-b989-5492eafa07d3"
            PathPattern: "/admin/api/*"
            SmoothStreaming: false
            TargetOriginId: "api.career-change-supporter.com"
            ViewerProtocolPolicy: "https-only"
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: "/"
            ResponseCode: "403"
            ErrorCachingMinTTL: 10
        Comment: ""
        PriceClass: "PriceClass_All"
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateManagerCertificate2
          CloudFrontDefaultCertificate: false
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
        Restrictions:
          GeoRestriction:
            RestrictionType: "none"
        WebACLId: !GetAtt WAFv2WebACL2.Arn
        HttpVersion: "http2"
        DefaultRootObject: "index.html"
        IPV6Enabled: true
        Logging:
          Bucket: !Sub "${S3Bucket3}.s3.amazonaws.com"
          IncludeCookies: false
          Prefix: ""
  CloudFrontCloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "access-identity-d750795057218d47535f0b418ccbb4f6.s3.ap-northeast-1.amazonaws.com"
  CloudFrontOriginAccessControl:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${S3Bucket2}.s3.ap-northeast-1.amazonaws.com"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: "always"
        SigningProtocol: "sigv4"
  CloudFrontOriginAccessControl2:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${S3Bucket}.s3.ap-northeast-1.amazonaws.com"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: "always"
        SigningProtocol: "sigv4"
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "ccs-admin-app"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  S3Bucket2:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "ccs-user-app"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2008-10-17"
        Id: "PolicyForCloudFrontPrivateContent"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution2}"
  S3BucketPolicy2:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket2
      PolicyDocument:
        Version: "2008-10-17"
        Id: "PolicyForCloudFrontPrivateContent"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket2}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CcsUserServiceRequestController}"
  WAFv2WebACL2:
    Type: "AWS::WAFv2::WebACL"
    Properties:
      Name: "AdminCcsCloudFrontWebAcl"
      Description: ""
      DefaultAction:
        Block: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: "AdminCcsCloudFrontWebAcl"
      Scope: "CLOUDFRONT"
      Rules:
        - Name: "OnlyAllowFromMyIP"
          Priority: 0
          Action:
            Allow: {}
          Statement:
            OrStatement:
              Statements:
                - IPSetReferenceStatement:
                    ARN: !GetAtt WAFv2IPSet.Arn
                - IPSetReferenceStatement:
                    ARN: !GetAtt WAFv2IPSet2.Arn
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "OnlyAllowFromMyIP"
  WAFv2IPSet:
    Type: "AWS::WAFv2::IPSet"
    Properties:
      Name: "MyIPv4"
      Description: ""
      IPAddressVersion: "IPV4"
      Addresses:
        - "106.72.35.128/32"
      Scope: "CLOUDFRONT"
  WAFv2IPSet2:
    Type: "AWS::WAFv2::IPSet"
    Properties:
      Name: "MyIPv6"
      Description: ""
      IPAddressVersion: "IPV6"
      Addresses:
        - "240b:0010:2380:5800:4cc2:b27c:9666:7d33/128"
        - "240b:0010:2380:5800:a057:65c8:dd72:542d/128"
      Scope: "CLOUDFRONT"
  S3Bucket3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "admin-ccs-cloudfront-logs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerPreferred"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  S3Bucket4:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "ccs-cloudfront-logs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerPreferred"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    CertificateManagerCertificate2:
      Type: "AWS::CertificateManager::Certificate"
      Properties:
        DomainName: "admin.career-change-supporter.com"
        SubjectAlternativeNames:
          - "admin.career-change-supporter.com"
        DomainValidationOptions:
          - DomainName: "admin.career-change-supporter.com"
            ValidationDomain: "admin.career-change-supporter.com"
        CertificateTransparencyLoggingPreference: "ENABLED"
    Route53RecordSet:
      Type: "AWS::Route53::RecordSet"
      Properties:
        Name: !Ref Route53RecordSet2
        Type: "A"
        AliasTarget:
          HostedZoneId: "Z2FDTNDATAQYW2"
          DNSName: !Sub "${CcsUserServiceRequestController.DomainName}."
          EvaluateTargetHealth: false
        HostedZoneId: "Z027771334FILNAP83QUT"
    Route53RecordSet2:
      Type: "AWS::Route53::RecordSet"
      Properties:
        Name: "career-change-supporter.com."
        Type: "AAAA"
        AliasTarget:
          HostedZoneId: "Z2FDTNDATAQYW2"
          DNSName: !Sub "${CcsUserServiceRequestController.DomainName}."
          EvaluateTargetHealth: false
        HostedZoneId: "Z027771334FILNAP83QUT"
    Route53RecordSet3:
      Type: "AWS::Route53::RecordSet"
      Properties:
        Name: !Sub "admin.${Route53RecordSet}"
        Type: "A"
        AliasTarget:
          HostedZoneId: "Z2FDTNDATAQYW2"
          DNSName: !Sub "${CloudFrontDistribution2.DomainName}."
          EvaluateTargetHealth: false
        HostedZoneId: "Z027771334FILNAP83QUT"
    Route53RecordSet4:
      Type: "AWS::Route53::RecordSet"
      Properties:
        Name: !Sub "admin.${Route53RecordSet}"
        Type: "AAAA"
        AliasTarget:
          HostedZoneId: "Z2FDTNDATAQYW2"
          DNSName: !Sub "${CloudFrontDistribution2.DomainName}."
          EvaluateTargetHealth: false
        HostedZoneId: "Z027771334FILNAP83QUT"

# S3の方から一時コピー
# S3BucketPolicy:
#     Type: "AWS::S3::BucketPolicy"
#     Properties:
#         Bucket: !Ref CcsUserAppStore
#         PolicyDocument: 
#             Version: "2008-10-17"
#             Id: "PolicyForCloudFrontPrivateContent"
#             Statement: 
#               - 
#                 Sid: "AllowCloudFrontServicePrincipal"
#                 Effect: "Allow"
#                 Principal: 
#                     Service: "cloudfront.amazonaws.com"
#                 Action: "s3:GetObject"
#                 Resource: !Sub "arn:aws:s3:::${CcsUserAppStore}/*"
#                 Condition: 
#                     StringEquals: 
#                         "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/E1BL2NRJQYGUK9"

# S3BucketPolicy2:
#     Type: "AWS::S3::BucketPolicy"
#     Properties:
#         Bucket: !Ref CcsAdminAppStore
#         PolicyDocument: 
#             Version: "2008-10-17"
#             Id: "PolicyForCloudFrontPrivateContent"
#             Statement: 
#               - 
#                 Sid: "AllowCloudFrontServicePrincipal"
#                 Effect: "Allow"
#                 Principal: 
#                     Service: "cloudfront.amazonaws.com"
#                 Action: "s3:GetObject"
#                 Resource: !Sub "arn:aws:s3:::${CcsAdminAppStore}/*"
#                 Condition: 
#                     StringEquals: 
#                         "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/E3GETAQTKY7CA5"
