AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  # prodの場合はスタック名に"ProdSinglePageApplication"、devの場合はスタック名に"DevSinglePageApplication"を指定する
  Environment:
    Type: String
    AllowedValues:
      - prod
      - dev
Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]
Resources:
  CcsUserApp:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-user-app"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # CIの結果をアップロードするバケット。この中身をCcsUserAppへコピーすることでクライアントサイドのリリースを行う。
  CcsUserAppCiResultStorage:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-user-app-ci-result-storage"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CcsAdminApp:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-admin-app"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # CIの結果をアップロードするバケット。この中身をCcsAdminAppへコピーすることでクライアントサイドのリリースを行う。
  CcsAdminAppCiResultStorage:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-admin-app-ci-result-storage"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
# 他スタックに直接渡すことはないが、デバッグ用に実際に登録されたドメイン名は確認できるようにしておく
Outputs:
  CcsUserAppBucket:
    Value: !Ref CcsUserApp
  CcsUserAppStoreBucket:
    Value: !Ref CcsUserAppCiResultStorage
  CcsAdminAppBucket:
    Value: !Ref CcsAdminApp
  CcsAdminAppStoreBucket:
    Value: !Ref CcsAdminAppCiResultStorage
