AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  # prodの場合はスタック名に"ProdStaticFiles"、devの場合はスタック名に"DevStaticFiles"を指定する
  Environment:
    Type: String
    AllowedValues:
      - prod
      - dev
Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]
Resources:
  CcsUserApp:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-user-app"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CcsAdminApp:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ["-", [!If [IsProd, "prod", "dev"], "ccs-admin-app"]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  UserAppBucketName:
    Value: !Ref CcsUserApp
    Export:
      Name: !Sub "${AWS::StackName}-UserAppBucketName"
  AdminAppBucketName:
    Value: !Ref CcsAdminApp
    Export:
      Name: !Sub "${AWS::StackName}-AdminAppBucketName"
