// Copyright 2021 Ken Miura

use serde::Deserialize;
use std::error::Error;
use std::fmt::Display;

// TODO: リリース前に値を調整する (パスワードのストレッチングが2^BCRYPT_COST回実行される)
const BCRYPT_COST: u32 = 7;

/// Credential for login
/// 
/// This is passed from client, then generated by framework, so we cannnot check value when struct is generated.
/// Check values by [`Self::validate()`] before using this.
#[derive(Deserialize)]
pub struct Credential {
    pub email_address: String,
    pub password: String,
}

impl Credential {
    pub fn validate(&self) -> Result<(), CredentialError> {
        let _ = validate_email_address(&self.email_address)?;
        let _ = validate_password(&self.password)?;
        Ok(())
    }
}

fn validate_email_address(email_address: &str) -> Result<(), CredentialError> {
    todo!()
}

fn validate_password(password: &str) -> Result<(), CredentialError> {
    todo!()
}

/// Error related to [Credential]
#[derive(Debug)]
pub enum CredentialError {
}

impl Display for CredentialError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        todo!()
    }
}

impl Error for CredentialError {

}