[package]
name = "user_service"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-redis-session = "0.2.2"
async-session = "3.0.0"
axum = { version = "0.6.4", features = ["headers", "json", "multipart"] }
base64 = "0.21.0"
bytes = "1.3.0"
chrono = "0.4.23"
common = { path = "../common" }
dotenv = "0.15.0"
entity = { path = "../entity" }
hmac = "0.12.1"
hyper = { version = "0.14.23", features = ["full"] }
image = "0.24.5"
num_cpus = "1.15.0"
once_cell = "1.17.0"
opensearch = "2.0.0"
regex = "1.7.1"
rust_decimal = "1.27.0"
serde = { version = "1.0.152", features = ["derive"] }
sha2 = "0.10.6"
tokio = { version = "1.24.1", features = ["full"] }
tower = "0.4.13"
tower-cookies = { version = "0.8.0", features = ["axum-core", "signed"] }
tower-http = { version = "0.3.5", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
