[package]
name = "user_service"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-redis-session = "0.2.2"
async-session = "3.0.0"
axum = { version = "0.5.8", features = ["headers", "json", "multipart"] }
bytes = "1.1.0"
chrono = "0.4.19"
common = { path = "../common" }
dotenv = "0.15.0"
entity = { path = "../entity" }
hyper = { version = "0.14.18", features = ["full"] }
image = "0.24.1"
num_cpus = "1.13.1"
once_cell = "1.10.0"
regex = "1.5.5"
rust_decimal = "1.19.0"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tower-cookies = { version = "0.7.0", features = ["axum-core", "signed"] }
tower-http = { version = "0.3.0", features = ["trace"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
uuid = { version = "1.0.0", features = ["serde", "v4"] }
