# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
  
  cache:
    image: redis:6.2.1
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "8081:8080"

  smtp:
    image: schickling/mailcatcher:latest
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"

  localstack:
    image: localstack/localstack:latest
    restart: always
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data # 永続化したいデータの保存先（コンテナ内でのデータ保存先となるので、ホスト環境に必要な場合はvolumesでマウントする必要あり）
    # TODO: /docker-entrypoint-initaws.dに必要なs3バケットを作成するスクリプトを配置する（docker-entrypoint-initaws.d内のスクリプトはコンテナ生成時に実行される）
    #volumes:
    #   - ./docker/localstack/:/docker-entrypoint-initaws.d
    ports:
      - "4566:4566"

  elasticsearch:
    build:
      context: ./elastic_search_with_plugins
      dockerfile: Dockerfile
    restart: always
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    restart: always
    ports:
      - 5601:5601

volumes:
  es-data:
    driver: local