[package]
name = "common"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "chrono"] }
chrono = "0.4.19"
serde = { version = "1.0.127", features = ["derive"] }
regex = "1.5.4"
once_cell = "1.8.0"
bcrypt = "0.10.1"
axum = "0.4.0"
hyper = { version = "0.14.11", features = ["full"] }
tokio = { version = "1.10.0", features = ["full"] }
tower = "0.4.8"
tracing = "0.1.26"
http-body = "0.4.3"
lettre = "0.9"
lettre_email = "0.9"
reqwest = { version = "0.11.6", features = ["json"] }
