[package]
name = "common"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-redis-session = "0.2.2"
aws-config = "0.54.1"
aws-sdk-s3 = "0.24.0"
axum = { version = "0.6.4", features = ["macros"] }
bcrypt = "0.13.0"
chrono = "0.4.23"
cookie = "0.16.2"
entity = { path = "../entity" }
http = "0.2.8"
http-body = "0.4.5"
lettre = { version = "0.10.1", default-features = false, features = ["smtp-transport", "pool", "rustls-tls", "hostname", "builder", "tokio1", "tokio1-rustls-tls"] }
once_cell = "1.17.0"
opensearch = "2.0.0"
regex = "1.7.1"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_qs = "0.11.0"
tower-cookies = "0.8.0"
tracing = "0.1.37"
