[package]
name = "common"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.49.0"
aws-sdk-s3 = "0.19.0"
axum = "0.5.17"
bcrypt = "0.13.0"
chrono = "0.4.22"
cookie = "0.16.1"
http = "0.2.8"
http-body = "0.4.5"
lettre = { version = "0.10.0", default-features = false, features = ["smtp-transport", "pool", "rustls-tls", "hostname", "builder", "tokio1", "tokio1-rustls-tls"] }
once_cell = "1.15.0"
opensearch = "2.0.0"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.81"
serde_qs = "0.10.1"
tower-cookies = "0.7.0"
tracing = "0.1.37"
