[package]
name = "common"
version = "0.1.0"
authors = ["kmiura <ken.miura1102@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.13.0"
aws-sdk-s3 = "0.13.0"
axum = "0.5.8"
bcrypt = "0.13.0"
chrono = "0.4.19"
cookie = "0.16.0"
http = "0.2.6"
http-body = "0.4.4"
lettre = "0.9"
lettre_email = "0.9"
once_cell = "1.10.0"
opensearch = "2.0.0"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
tower-cookies = "0.7.0"
tracing = "0.1.34"
