export const SET_PASSWORD_UPDATE_RESULT_MESSAGE = 'setPasswordUpdateResultMessage'
export const SET_IDENTITY = 'setIdentity'
export const SET_FEE_PER_HOUR_IN_YEN = 'setFeePerHourInYen'
export const SET_BANK_ACCOUNT = 'setBankAccount'
export const SET_CONSULTANT_SEARCH_PARAM = 'setConsultantSearchParam'
export const SET_RECOVERY_CODE = 'setRecoveryCode'
