//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "ccs_schema",
    table_name = "approved_update_identity_req"
)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub appr_upd_identity_req_id: i64,
    pub user_account_id: i64,
    pub last_name: String,
    pub first_name: String,
    pub last_name_furigana: String,
    pub first_name_furigana: String,
    pub date_of_birth: Date,
    pub prefecture: String,
    pub city: String,
    pub address_line1: String,
    pub address_line2: Option<String>,
    pub telephone_number: String,
    pub image1_file_name_without_ext: String,
    pub image2_file_name_without_ext: Option<String>,
    pub approved_at: DateTimeWithTimeZone,
    pub approved_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
