//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub mod prelude;

pub mod admin_account;
pub mod career_info;
pub mod consulting_fee;
pub mod create_identity_info_req;
pub mod identity_info;
pub mod new_password;
pub mod tenant;
pub mod terms_of_use;
pub mod update_identity_info_req;
pub mod user_account;
pub mod user_temp_account;
