//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::admin_account::Entity as AdminAccount;
pub use super::career_info::Entity as CareerInfo;
pub use super::consulting_fee::Entity as ConsultingFee;
pub use super::create_identity_info_req::Entity as CreateIdentityInfoReq;
pub use super::identity_info::Entity as IdentityInfo;
pub use super::new_password::Entity as NewPassword;
pub use super::tenant::Entity as Tenant;
pub use super::terms_of_use::Entity as TermsOfUse;
pub use super::update_identity_info_req::Entity as UpdateIdentityInfoReq;
pub use super::user_account::Entity as UserAccount;
pub use super::user_temp_account::Entity as UserTempAccount;
