#!/bin/bash
set -eu

NEW_PASSWORD=${NEW_DB_MASTER_PASSWORD:-${DB_MASTER_PASSWORD}}

echo "${DB_HOST}:${DB_PORT}:*:${DB_MASTER_USER}:${DB_MASTER_PASSWORD}" > ~/.pgpass
chmod 600 ~/.pgpass

psql -h "${DB_HOST}" -p "${DB_PORT}" -v ON_ERROR_STOP=1 --username "${DB_MASTER_USER}" <<-EOSQL
    ALTER ROLE "${DB_MASTER_USER}" with PASSWORD '${NEW_PASSWORD}';
    CREATE ROLE ccs;
    GRANT ccs TO ${DB_MASTER_USER};
    CREATE ROLE user_app WITH LOGIN PASSWORD '${USER_APP_PASSWORD}';
    CREATE ROLE admin_app WITH LOGIN PASSWORD '${ADMIN_APP_PASSWORD}';
    CREATE DATABASE ccs_db WITH OWNER = ccs TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C';
EOSQL

rm ~/.pgpass
