export const SET_POST_IDENTITY_RESULT_MESSAGE = 'setPostIdentityResultMessage'
export const SET_PASSWORD_UPDATE_RESULT_MESSAGE = 'setPasswordUpdateResultMessage'
export const SET_IDENTITY = 'setIdentity'
export const SET_CAREERS = 'setCareers'
export const SET_FEE_PER_HOUR_IN_YEN = 'setFeePerHourInYen'
export const SET_BANK_ACCOUNT = 'setBankAccount'
