name: Update application
run-name: ${{ github.actor }} is starting workflow
on:
  workflow_dispatch
jobs:
  # Github Actionsの無料枠を使い切った場合を考慮し、ローカルでも実行できるようにコマンドをメインにジョブを作成する
  Update-Application:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # スタックの更新でタスク定義が更新される。サービスはタスク定義の最新を参照するようになっているので、タスク定義が更新されることにより自動的にローリングアップデートが開始される。
      - name: Update backend
        run: |
          if [ "${IS_PROD}" = "true" ]; then PREFIX="Prod"; else PREFIX="Dev"; fi
          aws cloudformation update-stack --stack-name "${PREFIX}AdminAccountTask" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=ServiceDomainName,UsePreviousValue=true
          aws cloudformation update-stack --stack-name "${PREFIX}AdminService" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=InquiryEmailAddress,UsePreviousValue=true ParameterKey=InstanceCount,UsePreviousValue=true ParameterKey=ServiceDomainName,UsePreviousValue=true ParameterKey=SystemEmailAddress,UsePreviousValue=true
          aws cloudformation update-stack --stack-name "${PREFIX}UserService" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=AdminEmailAddress,UsePreviousValue=true ParameterKey=InquiryEmailAddress,UsePreviousValue=true ParameterKey=MaxInstanceCount,UsePreviousValue=true ParameterKey=MinInstanceCount,UsePreviousValue=true ParameterKey=ServiceDomainName,UsePreviousValue=true ParameterKey=SystemEmailAddress,UsePreviousValue=true
          aws cloudformation update-stack --stack-name "${PREFIX}DeleteExpiredTempAccounts" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=AdminEmailAddress,UsePreviousValue=true ParameterKey=SystemEmailAddress,UsePreviousValue=true ParameterKey=ScheduledTaskEnabled,UsePreviousValue=true
          aws cloudformation update-stack --stack-name "${PREFIX}DeleteExpiredPwdChangeReqs" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=AdminEmailAddress,UsePreviousValue=true ParameterKey=SystemEmailAddress,UsePreviousValue=true ParameterKey=ScheduledTaskEnabled,UsePreviousValue=true
          aws cloudformation update-stack --stack-name "${PREFIX}DeleteExpiredTempMfaSecrets" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=AdminEmailAddress,UsePreviousValue=true ParameterKey=SystemEmailAddress,UsePreviousValue=true ParameterKey=ScheduledTaskEnabled,UsePreviousValue=true
          aws cloudformation update-stack --stack-name "${PREFIX}DeleteExpiredConsultationReqs" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=AdminEmailAddress,UsePreviousValue=true ParameterKey=SystemEmailAddress,UsePreviousValue=true ParameterKey=ScheduledTaskEnabled,UsePreviousValue=true
          aws cloudformation update-stack --stack-name "${PREFIX}DeleteExpiredDeletedUserAccounts" --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true ParameterKey=AdminEmailAddress,UsePreviousValue=true ParameterKey=SystemEmailAddress,UsePreviousValue=true ParameterKey=ScheduledTaskEnabled,UsePreviousValue=true
        env:
          IS_PROD: ${{ vars.IS_PROD }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: json
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}
      - name: Update frontend
        run: |
          if [ "${IS_PROD}" = "true" ]; then PREFIX="prod"; else PREFIX="dev"; fi
          aws s3 sync "s3://${CCS_USER_APP_RELEASE_PREPARATION_S3_BUCKET}" "s3://${PREFIX}-ccs-user-app" --delete
          aws s3 sync "s3://${CCS_ADMIN_APP_RELEASE_PREPARATION_S3_BUCKET}" "s3://${PREFIX}-ccs-admin-app" --delete
          aws cloudfront create-invalidation --distribution-id "${CCS_USER_APP_DISTRIBUTION_ID}" --paths "/*" --region "us-east-1"
          aws cloudfront create-invalidation --distribution-id "${CCS_ADMIN_APP_DISTRIBUTION_ID}" --paths "/*" --region "us-east-1"
        env:
          IS_PROD: ${{ vars.IS_PROD }}
          CCS_USER_APP_RELEASE_PREPARATION_S3_BUCKET: ${{ vars.CCS_USER_APP_RELEASE_PREPARATION_S3_BUCKET }}
          CCS_ADMIN_APP_RELEASE_PREPARATION_S3_BUCKET: ${{ vars.CCS_ADMIN_APP_RELEASE_PREPARATION_S3_BUCKET }}
          CCS_USER_APP_DISTRIBUTION_ID: ${{ vars.CCS_USER_APP_DISTRIBUTION_ID }}
          CCS_ADMIN_APP_DISTRIBUTION_ID: ${{ vars.CCS_ADMIN_APP_DISTRIBUTION_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: json
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}