name: Update setup tool
run-name: ${{ github.actor }} is starting workflow
on:
  workflow_dispatch
jobs:
  # Github Actionsの無料枠を使い切った場合を考慮し、ローカルでも実行できるようにコマンドをメインにジョブを作成する
  Update-Setup-Tool:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update setup tool
        run: |
          aws cloudformation update-stack --stack-name ProdDbInitializerTask --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true
          aws cloudformation update-stack --stack-name ProdMigrationToolMigrateTask --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true
          aws cloudformation update-stack --stack-name ProdMigrationToolRollbackTask --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true
          aws cloudformation update-stack --stack-name ProdIndexInitializerTask --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue="$(git rev-parse HEAD)" ParameterKey=Environment,UsePreviousValue=true
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: json
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_USER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}