name: Test, build and upload artifacts
run-name: ${{ github.actor }} is starting workflow
on: [push]
jobs:
  Test-Build-And-Upload-Artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test and build server side code
        run: |
          docker build --build-arg UID="`id -u`" --build-arg GID="`id -g`" --target development -t development -f .devcontainer/Dockerfile server/
          docker build --target server-test-and-build -t server-test-and-build -f .devcontainer/Dockerfile server/