name: Test, build and upload artifacts
run-name: ${{ github.actor }} is starting workflow
on:
  workflow_dispatch
jobs:
  # Github Actionsの無料枠を使い切った場合を考慮し、ローカルでも実行できるようにコマンドをメインにジョブを作成する
  Test-Build-And-Upload-Artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test and build server side code
        run: |
          docker build --build-arg UID="`id -u`" --build-arg GID="`id -g`" --target development -t development -f .devcontainer/Dockerfile server/
          docker build --target server-test-and-build -t server-test-and-build -f .devcontainer/Dockerfile server/
      - name: Create images
        run: |
          docker build --target delete-expired-temp-accounts -t ccs-delete-expired-temp-accounts:"$(git rev-parse HEAD)" -f .devcontainer/Dockerfile server/
      - name: Upload images
        run: |
          docker tag ccs-delete-expired-temp-accounts:"$(git rev-parse HEAD)" ${AWS_ECR_ACCOUNT}/ccs-delete-expired-temp-accounts:"$(git rev-parse HEAD)"
          docker push ${AWS_ECR_ACCOUNT}/ccs-delete-expired-temp-accounts:"$(git rev-parse HEAD)"
        env:
          AWS_ECR_ACCOUNT: ${{ vars.AWS_ECR_ACCOUNT }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: json
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_UPLOADER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_UPLOADER_AWS_SECRET_ACCESS_KEY }}
